# Generated by Django 5.2.14 on 2026-05-30 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('owner_name', models.CharField(max_length=120)),
                ('persona_pack', models.CharField(choices=[('tutor', 'Tutor / Coach'), ('event', 'Event Service'), ('agency', 'Freelancer / Agency'), ('consultant', 'Consultant'), ('creator', 'Creator'), ('home_service', 'Home Service')], max_length=40)),
                ('city', models.CharField(max_length=80)),
                ('whatsapp_number', models.CharField(max_length=32)),
                ('public_slug', models.SlugField(unique=True)),
                ('preferred_language', models.CharField(default='Hinglish', max_length=40)),
                ('brand_tone', models.CharField(default='Friendly professional', max_length=80)),
                ('payment_terms', models.TextField(blank=True)),
                ('growth_score', models.PositiveSmallIntegerField(default=0)),
                ('health_score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(max_length=180)),
                ('headline', models.CharField(max_length=240)),
                ('subtext', models.TextField()),
                ('primary_cta', models.CharField(max_length=80)),
                ('is_published', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('format', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('price_label', models.CharField(max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='businesses.catalogue')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='public_page', max_length=80)),
                ('extra_context', models.JSONField(blank=True, default=dict)),
                ('is_qualified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='businesses.business')),
                ('catalogue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='businesses.catalogueitem')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=32)),
                ('interested_service', models.CharField(max_length=140)),
                ('source', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
                ('expected_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_action', models.CharField(blank=True, max_length=220)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='businesses.business')),
                ('inquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='businesses.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('suggested_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='businesses.business')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='businesses.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('active_status', models.CharField(default='active', max_length=40)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='businesses.business')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.lead')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=80)),
                ('tone', models.CharField(default='friendly', max_length=40)),
                ('language', models.CharField(default='Hinglish', max_length=40)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='PageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_events', to='businesses.business')),
                ('catalogue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.catalogueitem')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=120)),
                ('service_name', models.CharField(max_length=140)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('part_paid', 'Part Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=32)),
                ('payment_mode', models.CharField(blank=True, max_length=60)),
                ('reference_note', models.CharField(blank=True, max_length=180)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='businesses.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='businesses.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_score', models.PositiveSmallIntegerField(default=0)),
                ('health_score', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='SetupProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('intake', 'Intake'), ('catalogue_draft', 'Catalogue Draft'), ('page_review', 'Page Review'), ('published', 'Published'), ('weekly_review', 'Weekly Review')], default='intake', max_length=40)),
                ('package_name', models.CharField(default='Starter Pilot', max_length=80)),
                ('owner_inputs_complete', models.BooleanField(default=False)),
                ('blockers', models.TextField(blank=True)),
                ('target_publish_date', models.DateField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_project', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='TrustProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('detail', models.TextField(blank=True)),
                ('proof_type', models.CharField(default='testimonial', max_length=60)),
                ('approved_for_public_use', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_proof', to='businesses.business')),
            ],
        ),
    ]
