# Generated by Django 5.2.14 on 2026-05-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='terms',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='timing_or_timeline',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_age_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='urgency_reason',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='payment',
            name='age_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='urgency_reason',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('client_context', models.CharField(max_length=140)),
                ('problem', models.TextField()),
                ('work_done', models.TextField()),
                ('outcome', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='businesses.business')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=180)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='businesses.catalogue')),
            ],
            options={
                'ordering': ['display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('asset_type', models.CharField(default='image', max_length=60)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField(blank=True)),
                ('placeholder_color', models.CharField(default='#d9cab3', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='businesses.business')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OperatorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(default='setup', max_length=60)),
                ('body', models.TextField()),
                ('is_blocker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_notes', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('detail', models.CharField(max_length=240)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_reasons', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_context', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('approved_for_public_use', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='businesses.business')),
            ],
            options={
                'ordering': ['display_order', 'customer_name'],
            },
        ),
    ]
